### ISSUE TITLE
user import in azure fails with key error. 

### ISSUE THREAD

**Issue by gobiviswanath** [mrchristine/db-migration#55]
user migration:

Export succeeded 

`python3 export_db.py --profile primary --users --azure
` 

Import failed: 

`python3 import_db.py --profile secondary --users --azure
`

Traceback (most recent call last):
File "import_db.py", line 180, in <module>
main()
File "import_db.py", line 41, in main
scim_c.import_all_users_and_groups()
File "/home/vivek/db-migration/dbclient/ScimClient.py", line 402, in import_all_users_and_groups
self.import_groups(group_dir)
File "/home/vivek/db-migration/dbclient/ScimClient.py", line 379, in import_groups
member_id_list.append(current_group_ids[m['display']])
KeyError: '9db832f5-bb53-4cc7-8250-912e676046d1'

**Comment by mrchristine** [comment]
What does the `azure_logs/groups/` folder contain?
Does the destination workspace have the groups defined, but missing the individual members? 

From the logs, all the groups should exist but the members should be missing according to the stacktrace. However, it's unclear how the key error is generated here since we don't use that type of id for group / user membership.

**Comment by mrchristine** [comment]
Does this environment use service principals?

**Comment by mrchristine** [comment]
It looks like there's a service principal defined and assigned to a particular group, which is causing the issue here. 
Is it possible to copy the group member response here? The logfile is under `azure_log/groups/group_name` file.

**Comment by mrchristine** [comment]
Filtering out service principals and we will need a feature enhancement to move those over. It's current a feature request to get that supported.
